version: '3.8'

services: 
    mysqlcn:
        image: mysql:8.0
        restart: unless-stopped
        env_file: ./.env
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
            - MYSQL_DATABASE=$MYSQLDB_DATABASE
        # ports:
        #     - "3310:3306"
        volumes:
            - db:/var/lib/mysql 
        
    app:
        depends_on:
            - mysqlcn
       # build: . 
        image: makremzitoun/inventory-app
        restart: on-failure
        env_file: ./.env
        ports:
            - 8080:8080
        environment:
              SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqlcn:3306/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
                
        volumes:
            - .m2:/root/.m2
        stdin_open: true
        tty: true
       


volumes:
    db:
